<?php 
$active = 'Preventive Maintenance';
$container = '.container-fuid{overflow: hidden;background: url(imgs/mc.jpg); background-position: center !important;background-size: cover !important;transition: .5s;} 
    	.bg-rgba{background: rgba(0,0,0,0.8); height: 350px;} 
@media (max-width:992px){
	.bg-rgba{height: 300px;}
}    	';
require 'header.php'; 
    	?>

	<h3 class="pt-5 display-4 text-light ani1 text-center" style="font-size: 35px !important;" id="head"><?php if (isset($_GET['pg'])) { echo($_GET['pg']); } ?></h3>
			</div>
</div>
</div>
<?php 
if (isset($_GET['pg'])) {
	?>
	<div class="container p-5 ">
		<div class="seer">
			<p class="lead"><a href="Services.php" class="text-muted">Our Services</a> / <a href="Our_services.php?pg=Preventive-Maintenance" class="text-muted">Preventive-Maintenance</a> / <a href="" ><?php echo ($_GET['pg']); ?></a></p>
			<div id="trans">
			<?php
		if ($_GET['pg'] == 'Air-Filter-Replacement') {
?>
						<h3 class="text-blue">The Basics Behind Air Filter Replacement Services</h3>
				<p>An air filter allows outside air into an engine’s intake manifold, where the air mixes with fuel to power a vehicle. Playing a defensive role, air filters prevent dirt particles, bugs, and other contaminants from entering the engine and causing destruction. Unfortunately, engine air filters lose effectiveness over time and require replacements. Drivers looking to replace an air filter can choose from three common types: paper, foam, and cotton. Paper air filters are usually cheap, but they generally wear out faster than their counterparts. Foam filters are a popular choice for off-road vehicles, because they have strong filtering capabilities. However, they also tend to clog engines if used and left unchecked. Cotton filters are commonly found on race cars, but can be also used as aftermarket upgrades on everyday vehicles. No matter the type of air filter in your vehicle, it is important to replace the air filter as needed. A dirty air filter can negatively affect gas mileage and make an engine run roughly.</p>
				<h3 class="text-blue">Why Should You Have Air Filter Replacement Services Performed?</h3>
				<p>To keep your vehicle at its best, it is recommended that you replace your air filter whenever you get your oil changed. However, your environment should also be considered when determining the right time to have your air filter replaced. Dirt roads can cause your air filter to wear more quickly than paved roads. The next time you get an oil change or notice your air filter performing poorly, give us a visit so our service staff can remove your old air filter and install a new one. Our staff understands that a dirty air filter can prevent clean air and fuel from mixing correctly. Let us help you find the right air filter so your vehicle can continue to perform well. We have the right tools to install your new air filter and will work hard to get you back on the road again.<br><br><span class="text-danger">Approx. Time: 15 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
				<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Air Filter Replacement Services</h3>
				<p>An air filter allows outside air into an engine’s intake manifold, where the air mixes with fuel to power a vehicle. Playing a defensive role, air filters prevent dirt particles, bugs, and other contaminants from entering the engine and causing destruction. Unfortunately, engine air filters lose effectiveness over time and require replacements. Drivers looking to replace an air filter can choose from three common types: paper, foam, and cotton. Paper air filters are usually cheap, but they generally wear out faster than their counterparts. Foam filters are a popular choice for off-road vehicles, because they have strong filtering capabilities. However, they also tend to clog engines if used and left unchecked. Cotton filters are commonly found on race cars, but can be also used as aftermarket upgrades on everyday vehicles. No matter the type of air filter in your vehicle, it is important to replace the air filter as needed. A dirty air filter can negatively affect gas mileage and make an engine run roughly.</p>
				<h3 class="text-blue">Why Should You Have Air Filter Replacement Services Performed?</h3>
				<p>To keep your vehicle at its best, it is recommended that you replace your air filter whenever you get your oil changed. However, your environment should also be considered when determining the right time to have your air filter replaced. Dirt roads can cause your air filter to wear more quickly than paved roads. The next time you get an oil change or notice your air filter performing poorly, give us a visit so our service staff can remove your old air filter and install a new one. Our staff understands that a dirty air filter can prevent clean air and fuel from mixing correctly. Let us help you find the right air filter so your vehicle can continue to perform well. We have the right tools to install your new air filter and will work hard to get you back on the road again.<br><br><span class="text-danger">Approx. Time: 15 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Air-Filter-Replacement';
					var head_f = 'Filtre à air de remplacement';
					var fre = `<h3 class="text-blue">L'essentiel des services de remplacement des filtres à air</h3><p>Un filtre à air laisse passer l’air extérieur dans le collecteur d’admission d’un moteur, où l’air se mélange au carburant pour alimenter un véhicule. Les filtres à air, qui jouent un rôle défensif, empêchent les particules de saleté, les insectes et autres contaminants de pénétrer dans le moteur et de les détruire. Malheureusement, les filtres à air des moteurs perdent de leur efficacité avec le temps et doivent être remplacés. Les conducteurs cherchant à remplacer un filtre à air peuvent choisir parmi trois types courants: le papier, la mousse et le coton. Les filtres à air en papier sont généralement bon marché, mais ils s'usent plus rapidement que leurs homologues. Les filtres en mousse sont un choix populaire pour les véhicules tout-terrain, car ils possèdent de fortes capacités de filtrage. Cependant, ils ont également tendance à obstruer les moteurs s'ils sont utilisés et laissés sans contrôle. Les filtres en coton sont couramment utilisés sur les voitures de course, mais peuvent également être utilisés pour la modernisation du marché secondaire. Peu importe le type de filtre à air de votre véhicule, il est important de remplacer le filtre à air si nécessaire. Un filtre à air encrassé peut avoir une incidence négative sur la consommation d'essence et forcer le moteur à tourner brusquement.</p><h3 class="text-blue">Pourquoi devriez-vous avoir des services de remplacement de filtre à air effectués?</h3><p>To keep your vehicle at its best, it is recommended that you replace your air filter whenever you get your oil changed. However, your environment should also be considered when determining the right time to have your air filter replaced. Dirt roads can cause your air filter to wear more quickly than paved roads. The next time you get an oil change or notice your air filter performing poorly, give us a visit so our service staff can remove your old air filter and install a new one. Our staff understands that a dirty air filter can prevent clean air and fuel from mixing correctly. Let us help you find the right air filter so your vehicle can continue to perform well. We have the right tools to install your new air filter and will work hard to get you back on the road again.<br><br><span class="text-danger">Approx. Time: 15 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>

<?php
}
 else if ($_GET['pg'] == 'Fuel-Injection') {
?>
						<h3 class="text-blue">The Basics Behind Fuel Injection Services</h3>
				<p>During a fuel injection, your vehicle’s fuel injectors are checked. Located in the intake manifold of the engine, fuel injectors use small nozzles to spray a mist of fuel that your engine can burn. Fuel injectors work with your throttle valve, which lets air into the engine whenever you use the gas pedal. When the valve opens, fuel injectors release the fuel mist so it mixes with the air. This fuel and air combination then enters the combustion chamber and helps your vehicle run. Over time, fuel injectors can become dirty. Clogged injectors can negatively affect your vehicle’s performance, leading to poor gas mileage and dirty exhaust emissions. Short trips make it especially easy for dirt and grime to build up inside the fuel injector nozzles. Because a healthy fuel injection system is important for overall vehicle maintenance, we advise you to keep watch over your fuel injectors and have them serviced as needed.</p>
				<h3 class="text-blue">Why Should You Have Fuel Injection Services Performed?</h3>
				<p>Are you ready for a fuel injection service? If you are experiencing lean misfire, poor acceleration, or rough idling, your fuel injection system may be to blame. When you encounter any of these issues or notice that your fuel injectors are clogged with dirt and grime, give us a visit. Our staff understands that dirty injectors can bring various problems to your vehicle, and we are equipped with the right tools for cleaning them. We will work hard to remove any build up in the nozzles of your injectors. In addition, we can check the pressure and volume of your fuel pump and pressure regulator. While inspecting your vehicle’s fuel injection system, we can also inspect fuel lines, fuel rails, throttle components, and fuel filters. We will also check to see if your vehicle’s sensors are performing correctly. When your vehicle is ready for a fuel injection service, don’t delay.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
				<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Fuel Injection Services</h3>
				<p>During a fuel injection, your vehicle’s fuel injectors are checked. Located in the intake manifold of the engine, fuel injectors use small nozzles to spray a mist of fuel that your engine can burn. Fuel injectors work with your throttle valve, which lets air into the engine whenever you use the gas pedal. When the valve opens, fuel injectors release the fuel mist so it mixes with the air. This fuel and air combination then enters the combustion chamber and helps your vehicle run. Over time, fuel injectors can become dirty. Clogged injectors can negatively affect your vehicle’s performance, leading to poor gas mileage and dirty exhaust emissions. Short trips make it especially easy for dirt and grime to build up inside the fuel injector nozzles. Because a healthy fuel injection system is important for overall vehicle maintenance, we advise you to keep watch over your fuel injectors and have them serviced as needed.</p>
				<h3 class="text-blue">Why Should You Have Fuel Injection Services Performed?</h3>
				<p>Are you ready for a fuel injection service? If you are experiencing lean misfire, poor acceleration, or rough idling, your fuel injection system may be to blame. When you encounter any of these issues or notice that your fuel injectors are clogged with dirt and grime, give us a visit. Our staff understands that dirty injectors can bring various problems to your vehicle, and we are equipped with the right tools for cleaning them. We will work hard to remove any build up in the nozzles of your injectors. In addition, we can check the pressure and volume of your fuel pump and pressure regulator. While inspecting your vehicle’s fuel injection system, we can also inspect fuel lines, fuel rails, throttle components, and fuel filters. We will also check to see if your vehicle’s sensors are performing correctly. When your vehicle is ready for a fuel injection service, don’t delay.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Fuel-Injection';
					var head_f = 'Injection de carburant';
					var fre = `<h3 class="text-blue">L'essentiel des services d'injection de carburant</h3><p>Lors d’une injection de carburant, les injecteurs de carburant de votre véhicule sont vérifiés. Situés dans la tubulure d'admission du moteur, les injecteurs de carburant utilisent de petites buses pour pulvériser un brouillard d'essence que votre moteur peut brûler. Les injecteurs de carburant fonctionnent avec votre papillon des gaz, ce qui laisse l'air entrer dans le moteur chaque fois que vous utilisez l'accélérateur. Lorsque la soupape s'ouvre, les injecteurs de carburant libèrent le brouillard de carburant afin qu'il se mélange à l'air. Cette combinaison carburant / air pénètre ensuite dans la chambre de combustion et aide votre véhicule à rouler. Au fil du temps, les injecteurs de carburant peuvent devenir sales. Des injecteurs bouchés peuvent affecter négativement les performances de votre véhicule, entraînant une faible consommation d'essence et des émissions polluantes. Les trajets courts facilitent l’accumulation de saleté et de crasse à l’intérieur des injecteurs de carburant. Parce qu'un système d'injection de carburant en bonne santé est important pour la maintenance générale du véhicule, nous vous conseillons de surveiller vos injecteurs de carburant et de les faire réviser au besoin.</p><h3 class="text-blue">Pourquoi devriez-vous faire exécuter des services d'injection de carburant?</h3><p>Êtes-vous prêt pour un service d'injection de carburant? Si vous rencontrez des ratés de combustion maigres, une faible accélération ou un ralenti accéléré, votre système d'injection de carburant peut être à blâmer. Si vous rencontrez un de ces problèmes ou si vous remarquez que vos injecteurs de carburant sont encrassés par de la terre et de la saleté, rendez-nous visite. Notre personnel comprend que des injecteurs sales peuvent poser divers problèmes à votre véhicule et nous sommes équipés des outils appropriés pour les nettoyer. Nous allons travailler dur pour éliminer toute accumulation dans les buses de vos injecteurs. De plus, nous pouvons vérifier la pression et le volume de votre pompe à carburant et de votre régulateur de pression. Lors de l’inspection du système d’injection de carburant de votre véhicule, nous pouvons également inspecter les canalisations de carburant, les rampes de carburant, les composants de papillon des gaz et les filtres à carburant. Nous vérifierons également si les capteurs de votre véhicule fonctionnent correctement. Lorsque votre véhicule est prêt pour un service d’injection de carburant, ne tardez pas.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>


<?php
}
 else if ($_GET['pg'] == 'Oil-and-Filter-Change') {
?>
						<h3 class="text-blue">The Basics Behind Oil and Filter Change Services</h3>
				<p>Oil is a lubricant that keeps your vehicle functioning properly. Oil plays an essential role in the engine of your vehicle, where it helps alleviate friction between various moving components. Without the protective layer that oil provides, the heat created from friction would melt an engine’s parts together. As oil runs through your vehicle’s system, it also collects sludge, grime, and other contaminants that can harm the engine. In turn, the oil filter catches these contaminants and helps to prevent them from mixing with the oil. However, the filter can only hold so much. Over time, the small bits and miscellaneous muck will break down the filter’s defenses. When this happens, the result is dirty oil. In addition to being less effective overall, dirty oil can cause permanent damage to some parts of your vehicle. As such, oil and filter changes are considered an important part of vehicle maintenance.</p>
				<h3 class="text-blue">Why Should You Have Oil and Filter Change Services Performed?</h3>
				<p>Are you in need of an oil and filter change or uncertain about the last time you had this service done? Allow us to help. Our expert staff can tend to your vehicle and assist you with any questions you may have in regard to our oil change and filter change process. If you are uncertain about what grade of oil is best for your vehicle, or if you are curious about the differences between synthetic, semi-synthetic, and conventional oil, we are happy to share our knowledge. Similarly, we can go over the micron ratings of different oil filters to help match you with the best possible oil filter. Simply contact us online or give us a call when you are ready to change your oil and filter.<br><br><span class="text-danger">Approx. Time: 30 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Oil and Filter Change Services</h3>
				<p>Oil is a lubricant that keeps your vehicle functioning properly. Oil plays an essential role in the engine of your vehicle, where it helps alleviate friction between various moving components. Without the protective layer that oil provides, the heat created from friction would melt an engine’s parts together. As oil runs through your vehicle’s system, it also collects sludge, grime, and other contaminants that can harm the engine. In turn, the oil filter catches these contaminants and helps to prevent them from mixing with the oil. However, the filter can only hold so much. Over time, the small bits and miscellaneous muck will break down the filter’s defenses. When this happens, the result is dirty oil. In addition to being less effective overall, dirty oil can cause permanent damage to some parts of your vehicle. As such, oil and filter changes are considered an important part of vehicle maintenance.</p>
				<h3 class="text-blue">Why Should You Have Oil and Filter Change Services Performed?</h3>
				<p>Are you in need of an oil and filter change or uncertain about the last time you had this service done? Allow us to help. Our expert staff can tend to your vehicle and assist you with any questions you may have in regard to our oil change and filter change process. If you are uncertain about what grade of oil is best for your vehicle, or if you are curious about the differences between synthetic, semi-synthetic, and conventional oil, we are happy to share our knowledge. Similarly, we can go over the micron ratings of different oil filters to help match you with the best possible oil filter. Simply contact us online or give us a call when you are ready to change your oil and filter.<br><br><span class="text-danger">Approx. Time: 30 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Oil-and-Filter-Change';
					var head_f = `Changement d'huile et de filtre`;
					var fre = `<h3 class="text-blue">L'essentiel des services de changement d'huile et de filtre</h3><p>L'huile est un lubrifiant qui maintient votre véhicule en état de fonctionner correctement. L’huile joue un rôle essentiel dans le moteur de votre véhicule car elle contribue à réduire les frictions entre différents composants en mouvement. Sans la couche de protection fournie par l’huile, la chaleur créée par le frottement ferait fondre les pièces d’un moteur. Au fur et à mesure que l'huile traverse le système de votre véhicule, elle recueille également la boue, la saleté et d'autres contaminants pouvant nuire au moteur. À son tour, le filtre à huile capte ces contaminants et aide à les empêcher de se mélanger à l'huile. Cependant, le filtre ne peut en contenir plus. Au fil du temps, les petites particules et les débris divers vont détruire les défenses du filtre. Lorsque cela se produit, le résultat est de l'huile sale. En plus d'être globalement moins efficace, une huile sale peut causer des dommages permanents à certaines parties de votre véhicule. En tant que tels, les changements d'huile et de filtres sont considérés comme une partie importante de l'entretien des véhicules.</p><h3 class="text-blue">Pourquoi devriez-vous faire effectuer des services de changement d'huile et de filtration?</h3><p>Avez-vous besoin d'un changement d'huile ou de filtre ou avez-vous des doutes sur la dernière fois où vous avez eu ce service? Permettez-nous d'aider. Notre personnel expert peut s'occuper de votre véhicule et vous aider avec toutes les questions que vous pourriez avoir concernant notre processus de changement d'huile et de filtrage. Si vous n'êtes pas sûr de la qualité d'huile qui convient le mieux à votre véhicule ou si vous êtes curieux des différences entre les huiles synthétiques, semi-synthétiques et conventionnelles, nous serons heureux de partager nos connaissances. De même, nous pouvons passer au micron de différents filtres à huile pour vous faire correspondre au meilleur filtre à huile possible. Contactez-nous simplement en ligne ou appelez-nous lorsque vous serez prêt à changer votre huile et votre filtre.<br><br><span class="text-danger">Approx. Time: 30 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>
<?php
}
 else if ($_GET['pg'] == 'Spring-Checkup') {
?>
						<h3 class="text-blue">The Basics Behind Spring Checkup Services</h3>
				<p>A spring checkup helps prepare your vehicle for the hot months of summer. During a checkup, multiple components may be reviewed for efficiency. The battery, an essential component that works particularly hard during the winter months, may be tested and its age considered. If snow tires are equipped on your vehicle, a spring checkup is a good time to replace them with summer tires. In addition, the tread depth and tire pressure of summer tires may be looked at because they can affect gas mileage. Belts and hoses may also be checked to make sure they are intact and sturdy. Potholes usually become more pronounced after winter, so it is important to see if the shocks and struts are in healthy condition as well. From the starting and charging system to the transmission fluid and antifreeze levels, there is much to review during a spring inspection. However, a checkup can ultimately help keep your vehicle safe and save you money in the long run.</p>
				<h3 class="text-blue">Why Should You Have Spring Checkup Services Performed?</h3>
				<p>Before summer begins, it is advisable that you seek a spring maintenance service for your vehicle prior to the summer months. Our knowledgeable staff is equipped with the right tools for testing various components in your vehicle. From your wiper blades to your tires, we are ready to look over the various parts and components that make up your vehicle and help make sure they perform well, and continue to perform well for you. If you are curious about what we check, why we check it, or how we test it, just ask. We are happy to help you learn more about our spring maintenance checklist.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Spring Checkup Services</h3>
				<p>A spring checkup helps prepare your vehicle for the hot months of summer. During a checkup, multiple components may be reviewed for efficiency. The battery, an essential component that works particularly hard during the winter months, may be tested and its age considered. If snow tires are equipped on your vehicle, a spring checkup is a good time to replace them with summer tires. In addition, the tread depth and tire pressure of summer tires may be looked at because they can affect gas mileage. Belts and hoses may also be checked to make sure they are intact and sturdy. Potholes usually become more pronounced after winter, so it is important to see if the shocks and struts are in healthy condition as well. From the starting and charging system to the transmission fluid and antifreeze levels, there is much to review during a spring inspection. However, a checkup can ultimately help keep your vehicle safe and save you money in the long run.</p>
				<h3 class="text-blue">Why Should You Have Spring Checkup Services Performed?</h3>
				<p>Before summer begins, it is advisable that you seek a spring maintenance service for your vehicle prior to the summer months. Our knowledgeable staff is equipped with the right tools for testing various components in your vehicle. From your wiper blades to your tires, we are ready to look over the various parts and components that make up your vehicle and help make sure they perform well, and continue to perform well for you. If you are curious about what we check, why we check it, or how we test it, just ask. We are happy to help you learn more about our spring maintenance checklist.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Spring-Checkup';
					var head_f = `Bilan de printemps`;
					var fre = `<h3 class="text-blue">Les bases des services de vérification printanière</h3><p>Un bilan de printemps permet de préparer votre véhicule pour les chauds mois d’été. Au cours d'un bilan, plusieurs composants peuvent être examinés pour en améliorer l'efficacité. La batterie, composant essentiel particulièrement actif en hiver, peut être testée et son âge pris en compte. Si votre véhicule est équipé de pneus neige, une vérification au printemps est un bon moment pour les remplacer par des pneus été. En outre, la profondeur de la bande de roulement et la pression des pneus d'été peuvent être examinées car elles peuvent affecter la consommation d'essence. Les courroies et les flexibles peuvent également être vérifiés pour s’assurer qu’ils sont intacts et robustes. Les nids-de-poule deviennent généralement plus prononcés après l’hiver; il est donc important de vérifier si les amortisseurs et les contrefiches sont également en bon état. Du système de démarrage et de charge aux niveaux de liquide de transmission et d'antigel, il y a beaucoup à revoir lors d'une inspection de printemps. Cependant, un contrôle peut en fin de compte aider à protéger votre véhicule et vous faire économiser de l'argent à long terme.</p><h3 class="text-blue">Pourquoi devriez-vous faire effectuer des services de vérification du printemps?</h3><p>Avant le début de l'été, il est conseillé de faire appel à un service d'entretien de printemps pour votre véhicule avant les mois d'été. Notre personnel compétent est équipé des outils appropriés pour tester différents composants de votre véhicule. De vos balais d’essuie-glace à vos pneus, nous sommes prêts à examiner les différentes pièces et composants qui composent votre véhicule et à nous assurer de leur bon fonctionnement, ainsi que de leur bon fonctionnement pour vous. Si vous êtes curieux de savoir ce que nous vérifions, pourquoi nous le vérifions ou comment nous le testons, il vous suffit de demander. Nous sommes heureux de vous aider à en apprendre davantage sur notre liste de contrôle de la maintenance de printemps.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>

<?php
}
 else if ($_GET['pg'] == 'Winterization-Checkup') {
?>
						<h3 class="text-blue">The Basics Behind Winterization Checkup Services</h3>
				<p>When winter is near, many motorists begin winterizing their vehicles to prepare them for the cold, ice, and snow. Winterization involves checking and changing many different components. Coolant should be changed to help ensure that liquids do not freeze and prevent the engine from starting. Likewise, the starting and charging system should be checked. It is important to keep in mind that an old battery is especially prone to failure in winter, because cold weather can slow the chemical reaction required to generate electricity. Other items that may be checked include the windshield wiper blades and tires. During winter, increased precipitation can hinder visibility. As such, it is good to have working blades. Under winter driving conditions, underperforming tires can be especially dangerous. Many motorists switch their regular tires to snow tires, which tend to handle winter conditions better than regular tires. Ultimately, during pre-winter maintenance, our service staff will make sure that your vehicle is equipped to handle the tough winter conditions.</p>
				<h3 class="text-blue">Why Should You Have Winterization Checkup Services Performed?</h3>
				<p>Is your vehicle ready for winter? If not, we invite you to come in for our winterization service. Our knowledgeable staff can aid you in preparing your vehicle for harsh winter weather conditions. We can look over your brakes, belts, hoses, and other components. In addition, we can test your wiper blades and change your oil. If you feel it is time to swap your regular tires with a set of winter tires, just give us a call. Similarly, if you are uncertain about why a particular component is important to check or do not know what replacement will work best for your vehicle, we are happy to lend you our support and knowledge. When winter is coming, don’t delay. Contact us online or by phone and we will help you properly prepare it for the wintery weather.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Winterization Checkup Services</h3>
				<p>When winter is near, many motorists begin winterizing their vehicles to prepare them for the cold, ice, and snow. Winterization involves checking and changing many different components. Coolant should be changed to help ensure that liquids do not freeze and prevent the engine from starting. Likewise, the starting and charging system should be checked. It is important to keep in mind that an old battery is especially prone to failure in winter, because cold weather can slow the chemical reaction required to generate electricity. Other items that may be checked include the windshield wiper blades and tires. During winter, increased precipitation can hinder visibility. As such, it is good to have working blades. Under winter driving conditions, underperforming tires can be especially dangerous. Many motorists switch their regular tires to snow tires, which tend to handle winter conditions better than regular tires. Ultimately, during pre-winter maintenance, our service staff will make sure that your vehicle is equipped to handle the tough winter conditions.</p>
				<h3 class="text-blue">Why Should You Have Winterization Checkup Services Performed?</h3>
				<p>Is your vehicle ready for winter? If not, we invite you to come in for our winterization service. Our knowledgeable staff can aid you in preparing your vehicle for harsh winter weather conditions. We can look over your brakes, belts, hoses, and other components. In addition, we can test your wiper blades and change your oil. If you feel it is time to swap your regular tires with a set of winter tires, just give us a call. Similarly, if you are uncertain about why a particular component is important to check or do not know what replacement will work best for your vehicle, we are happy to lend you our support and knowledge. When winter is coming, don’t delay. Contact us online or by phone and we will help you properly prepare it for the wintery weather.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Winterization-Checkup';
					var head_f = `Bilan d'hivernage`;
					var fre = `<h3 class="text-blue">L'essentiel des services de vérification de la hivernage</h3><p>Lorsque l'hiver approche, de nombreux automobilistes commencent à hiverner leurs véhicules pour les préparer au froid, à la glace et à la neige. L'hivernage implique la vérification et la modification de nombreux composants différents. Le liquide de refroidissement doit être changé pour éviter que les liquides gèlent et empêcher le moteur de démarrer. De même, le système de démarrage et de charge doit être vérifié. Il est important de garder à l'esprit qu'une vieille batterie est particulièrement sujette aux pannes en hiver, car le temps froid peut ralentir la réaction chimique nécessaire à la production d'électricité. Les autres éléments pouvant être vérifiés comprennent les balais d’essuie-glace et les pneus. En hiver, l'augmentation des précipitations peut nuire à la visibilité. En tant que tel, il est bon d'avoir des lames qui fonctionnent. En hiver, les pneus peu performants peuvent être particulièrement dangereux. De nombreux automobilistes passent leurs pneus ordinaires à des pneus d'hiver, qui tendent à mieux supporter les conditions hivernales que les pneus ordinaires. En fin de compte, lors de l’entretien pré-hiver, notre personnel de service s’assurera que votre véhicule est équipé pour faire face aux conditions hivernales difficiles.</p><h3 class="text-blue">Pourquoi devriez-vous faire exécuter des services de vérification de l’hivernage?</h3><p>Votre véhicule est-il prêt pour l'hiver? Sinon, nous vous invitons à venir pour notre service de préparation pour l'hiver. Notre personnel compétent peut vous aider à préparer votre véhicule pour les rigueurs de l'hiver. Nous pouvons examiner vos freins, ceintures, flexibles et autres composants. De plus, nous pouvons tester vos balais d’essuie-glace et changer votre huile. Si vous pensez qu'il est temps d'échanger vos pneus ordinaires contre des pneus d'hiver, appelez-nous. De même, si vous ne savez pas pourquoi un composant particulier doit être vérifié ou si vous ne savez pas quel remplacement conviendra le mieux à votre véhicule, nous serons heureux de vous apporter notre soutien et nos connaissances. Lorsque l’hiver arrive, ne tardez pas. Contactez-nous en ligne ou par téléphone et nous vous aiderons à bien le préparer pour les conditions hivernales.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>

<?php
}
 else if ($_GET['pg'] == 'Wiper-Blades-Replacement') {
?>
						<h3 class="text-blue">The Basics Behind Wiper Blades Replacement Services</h3>
				<p>Wiper blades are responsible for helping drivers travel safely in inclement weather. In bad weather conditions like downpours, wiper blades can be activated to help keep a driver’s field of vision clear. Many vehicles have a single pair of wiper blades located on the front windshield, but some vehicles also contain a wiper blade on the rear windshield. Because they are located on the outside of your vehicle, wiper blades are prone to wear and will require replacements in time. Even if they are not heavily used, the blades should be replaced regularly because the material they are made of has its own lifespan. Generally, it is recommended that wiper blades be replaced every 6,000 miles or every six months. However, it is worth noting that surrounding weather conditions may alter the lifespan of the blades, so it is recommended that all drivers inquire about the best time to replace their specific wiper blades.</p>
				<h3 class="text-blue">Why Should You Have Wiper Blades Replacement Services Performed?</h3>
				<p>Do you know whether or not your windshield wiper blades need to be replaced? Our expert staff can help you determine when you should replace your wiper blades, and our knowledgeable employees can aid you in finding the proper replacement wiper blades. Our staff understands that wiper blades come in different sizes and types. If you don’t know what size wiper blades you need or whether or not your vehicle uses conventional blades or beam blades, we can help. We are happy to answer your questions and will strive to find you the best windshield wiper blades for your needs. If you need any help replacing your old blades with new ones, please let us know. Our staff looks forward to working with you through the windshield wiper blade replacement process.<br><br><span class="text-danger">Approx. Time: 15 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Wiper Blades Replacement Services</h3>
				<p>Wiper blades are responsible for helping drivers travel safely in inclement weather. In bad weather conditions like downpours, wiper blades can be activated to help keep a driver’s field of vision clear. Many vehicles have a single pair of wiper blades located on the front windshield, but some vehicles also contain a wiper blade on the rear windshield. Because they are located on the outside of your vehicle, wiper blades are prone to wear and will require replacements in time. Even if they are not heavily used, the blades should be replaced regularly because the material they are made of has its own lifespan. Generally, it is recommended that wiper blades be replaced every 6,000 miles or every six months. However, it is worth noting that surrounding weather conditions may alter the lifespan of the blades, so it is recommended that all drivers inquire about the best time to replace their specific wiper blades.</p>
				<h3 class="text-blue">Why Should You Have Wiper Blades Replacement Services Performed?</h3>
				<p>Do you know whether or not your windshield wiper blades need to be replaced? Our expert staff can help you determine when you should replace your wiper blades, and our knowledgeable employees can aid you in finding the proper replacement wiper blades. Our staff understands that wiper blades come in different sizes and types. If you don’t know what size wiper blades you need or whether or not your vehicle uses conventional blades or beam blades, we can help. We are happy to answer your questions and will strive to find you the best windshield wiper blades for your needs. If you need any help replacing your old blades with new ones, please let us know. Our staff looks forward to working with you through the windshield wiper blade replacement process.<br><br><span class="text-danger">Approx. Time: 15 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Wiper-Blades-Replacement';
					var head_f = `Balais d'essuie-glace-remplacement`;
					var fre = `<h3 class="text-blue">L'essentiel des services de remplacement de balais d'essuie-glace</h3><p>Les balais d’essuie-glace aident les conducteurs à se déplacer en toute sécurité par mauvais temps. Par mauvais temps, comme les averses, les balais d’essuie-glace peuvent être activés pour que le champ de vision du conducteur soit dégagé. De nombreux véhicules possèdent une seule paire de balais d'essuie-glace situés sur le pare-brise avant, mais certains véhicules comportent également un balai d'essuie-glace sur le pare-brise arrière. Parce qu'ils sont situés à l'extérieur de votre véhicule, les balais d'essuie-glace sont sujets à l'usure et devront être remplacés à temps. Même si elles ne sont pas très utilisées, les lames doivent être remplacées régulièrement car le matériau qui les compose a sa propre durée de vie. En règle générale, il est recommandé de remplacer les balais d'essuie-glace tous les 6 000 milles ou tous les six mois. Cependant, il convient de noter que les conditions météorologiques environnantes peuvent modifier la durée de vie des balais, il est donc recommandé à tous les conducteurs de s'informer du meilleur moment pour remplacer leurs balais d'essuie-glace spécifiques.</p><h3 class="text-blue">Pourquoi devriez-vous faire exécuter des services de remplacement de balais d'essuie-glace?</h3><p>Savez-vous si vos balais d’essuie-glace doivent être remplacés? Notre personnel expert peut vous aider à déterminer quand remplacer vos balais d'essuie-glace, et nos employés compétents peuvent vous aider à trouver le balai d'essuie-glace de remplacement qui convient. Notre personnel comprend que les balais d'essuie-glace existent en différentes tailles et types. Si vous ne savez pas de quelle taille de balais d’essuie-glace vous avez besoin ou si votre véhicule utilise des balais ou des balais classiques, nous pouvons vous aider. Nous sommes heureux de répondre à vos questions et nous efforcerons de vous trouver le meilleur balai d'essuie-glace pour vos besoins. Si vous avez besoin d'aide pour remplacer vos anciennes lames par de nouvelles, veuillez nous en informer. Notre personnel se réjouit de pouvoir travailler avec vous tout au long du processus de remplacement des balais d’essuie-glace.<br><br><span class="text-danger">Approx. Time: 15 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>

<?php
}
?>
</div>
</div>
</div>
<script type="text/javascript">
	var head = document.getElementById('head');
	var elem = document.getElementById('trans');
function lang_trans() {
		var lng = document.getElementById('lang').value;
		if (lng == 'fre') {
		head.innerHTML = head_f;
		trans.innerHTML = fre;
		}
		else if (lng = 'eng'){
		head.innerHTML = head_e;
		trans.innerHTML = eng;
		}

	}
</script>
<?php
}
require 'footer.php';
?>