<?php 
$active = 'Steering And Suspension';
$container = '.container-fuid{overflow: hidden;background: url(imgs/mc.jpg); background-position: center !important;background-size: cover !important;transition: .5s;} 
    	.bg-rgba{background: rgba(0,0,0,0.8); height: 350px;} 
@media (max-width:992px){
	.bg-rgba{height: 300px;}
} 	';
require 'header.php'; 
    	?>

	<h3 class="pt-5 display-4 text-light ani1 text-center" style="font-size: 35px !important;" id="head"><?php if (isset($_GET['pg'])) { echo($_GET['pg']); } ?></h3>
			</div>
</div>
</div>
<?php 
if (isset($_GET['pg'])) {
	?>
	<div class="container p-5 ">
		<div class="seer">
			<p class="lead"><a href="Services.php" class="text-muted">Our Services</a> / <a href="Our_services.php?pg=Steering-and-Suspension-System" class="text-muted">Steering-and-Suspension-System</a> / <a href="" ><?php echo ($_GET['pg']); ?></a></p>
			<div id="trans">
			<?php
		if ($_GET['pg'] == 'Ball-Joint') {
?>
						<h3 class="text-blue">The Basics Behind Ball Joint Replacement Services</h3>
				<p>The suspension system allows your tires to maintain constant contact with the road, especially on uneven surfaces like bumps and potholes. Ball joints are ball-and-socket joints located between the control arm and the steering knuckle. Ball joints act as the pivot point between the wheels and the rest of the suspension system. They are designed to allow for movement in two planes at once while providing ease of rotation in those planes. They allow a vehicle’s suspension system to move up or down while the wheels turn left or right. Vehicles with shocks have upper and lower ball joints, while many vehicles with struts have only lower ball joints. Some ball joints are load-bearing and will wear faster than normal ball joints. As an important suspension component, ball joints are designed to experience wear and tear, often in the form of friction. Like all suspension system components, ball joints have a maintenance schedule that can help prevent unexpected repairs or replacements.</p>
				<h3 class="text-blue">Why Should You Have Ball Joint Replacement Services Performed?</h3>
				<p>Upper and lower ball joints are designed to fit snugly inside a lubricated casing. If the casing loses lubrication, dries out, or the linkage becomes loose, wheel alignment may be affected. A loose ball joint can also result in suspension noise and uneven tire wear. Because ball joints act as the link between the wheels and other suspension components, a bad joint can conflict with normal steering capabilities. In extreme cases, a worn ball joint that fails may fall out of its casing and cause a collapse of the suspension system. Clunking sounds, poor handling, and unnatural pulling are all signs of bad ball joints. In some cases, ball joints may require replacements. If you plan on avoiding a ball joint failure, be sure to consult your owner’s manual for the maximum allowable wear on your suspension system’s ball joints. Our replacement ball joints will restore full functionality to your suspension system.<br><br><span class="text-danger">Approx. Time: 120 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
				<script type="text/javascript">
					var eng = `The Basics Behind Ball Joint Replacement Services</h3>
				<p>The suspension system allows your tires to maintain constant contact with the road, especially on uneven surfaces like bumps and potholes. Ball joints are ball-and-socket joints located between the control arm and the steering knuckle. Ball joints act as the pivot point between the wheels and the rest of the suspension system. They are designed to allow for movement in two planes at once while providing ease of rotation in those planes. They allow a vehicle’s suspension system to move up or down while the wheels turn left or right. Vehicles with shocks have upper and lower ball joints, while many vehicles with struts have only lower ball joints. Some ball joints are load-bearing and will wear faster than normal ball joints. As an important suspension component, ball joints are designed to experience wear and tear, often in the form of friction. Like all suspension system components, ball joints have a maintenance schedule that can help prevent unexpected repairs or replacements.</p>
				<h3 class="text-blue">Why Should You Have Ball Joint Replacement Services Performed?</h3>
				<p>Upper and lower ball joints are designed to fit snugly inside a lubricated casing. If the casing loses lubrication, dries out, or the linkage becomes loose, wheel alignment may be affected. A loose ball joint can also result in suspension noise and uneven tire wear. Because ball joints act as the link between the wheels and other suspension components, a bad joint can conflict with normal steering capabilities. In extreme cases, a worn ball joint that fails may fall out of its casing and cause a collapse of the suspension system. Clunking sounds, poor handling, and unnatural pulling are all signs of bad ball joints. In some cases, ball joints may require replacements. If you plan on avoiding a ball joint failure, be sure to consult your owner’s manual for the maximum allowable wear on your suspension system’s ball joints. Our replacement ball joints will restore full functionality to your suspension system.<br><br><span class="text-danger">Approx. Time: 120 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Ball-Joint';
					var head_f = `Joint à rotule`;
					var fre = `<h3 class="text-blue">L'essentiel des services de remplacement de joints à rotule</h3><p>Le système de suspension permet à vos pneus de rester en contact permanent avec la route, en particulier sur les surfaces inégales telles que les bosses et les nids de poule. Les joints à rotule sont des joints à rotule situés entre le bras de commande et la fusée d'essieu. Les joints à rotule agissent comme le point de pivotement entre les roues et le reste du système de suspension. Ils sont conçus pour permettre le mouvement dans deux plans à la fois tout en offrant une facilité de rotation dans ces plans. Ils permettent au système de suspension du véhicule de monter ou de descendre pendant que les roues tournent à gauche ou à droite. Les véhicules avec amortisseurs ont des joints à rotule supérieurs et inférieurs, alors que beaucoup de véhicules avec des jambes de force ne possèdent que des joints à rotule inférieurs. Certains joints à rotule sont porteurs et s'useront plus rapidement que les joints à rotule normaux. En tant que composant important de la suspension, les joints à rotule sont conçus pour résister à l'usure, souvent sous la forme de frottements. Comme tous les composants du système de suspension, les joints à rotule ont un programme d'entretien qui peut aider à prévenir les réparations ou les remplacements imprévus.</p><h3 class="text-blue">Pourquoi devriez-vous faire exécuter des services de remplacement de joints à rotule?</h3><p>Les joints à rotule supérieurs et inférieurs sont conçus pour s'intégrer parfaitement dans un boîtier lubrifié. Si le carter perd de la lubrification, se dessèche ou si la liaison se desserre, l'alignement des roues peut être affecté. Une rotule desserrée peut également entraîner des bruits de suspension et une usure inégale des pneus. Les rotules agissant comme un lien entre les roues et les autres composants de la suspension, une mauvaise articulation peut entrer en conflit avec les capacités de direction normales. Dans des cas extrêmes, une rotule usée qui tombe en panne peut tomber de son boîtier et provoquer un effondrement du système de suspension. Des bruits de clunking, une mauvaise manipulation et des tractions artificielles sont autant de signes de mauvaises rotules. Dans certains cas, les joints à rotule peuvent nécessiter un remplacement. Si vous prévoyez d’éviter une défaillance de la rotule, consultez votre manuel du propriétaire pour connaître l’usure maximale admissible des rotules de votre système de suspension. Nos joints à rotule de remplacement restaureront toutes les fonctionnalités de votre système de suspension.<br><br><span class="text-danger">Approx. Time: 120 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>

<?php
}
 else if ($_GET['pg'] == 'Tie-Rod') {
?>
						<h3 class="text-blue">The Basics Behind Inner Tie Rod & Outer Tie Rod Replacement Services</h3>
				<p>Tires & Service
Regardless of the type of steering system in your vehicle, you use inner and outer tie rods. As an important part of your vehicle’s steering and suspension system, tie rods act as the link between your vehicle’s steering system and the steering arm, which is attached to the steering wheel. When you turn the steering wheel, the steering arm moves the front wheels through the steering system. The inner and outer tie rods connect to the steering arm in order to move the wheels of your vehicle. In the common rack-and-pinion steering system, the inner tie rods connect to the steering rack while the outer tie rods connect to the steering arms. The tie rods make steering and turning possible by moving your wheels in the desired direction. Without properly functioning tie rods, the steering mechanism would no longer operate as intended. Because inner and outer tie rods play such a significant role, replacing tie rods as necessary is important for overall vehicle maintenance.</p>
				<h3 class="text-blue">Why Should You Have Inner Tie Rod & Outer Tie Rod Replacement Services Performed?</h3>
				<p>Difficult, erratic, and unexpected steering are signs that your tie rods—inner, outer, or both—might need to be replaced. One indication that your tie rods may be loose is excessive and uneven tire wear. Vibrations and clunking noises emanating from the front of your vehicle are another sign. Steering that pulls or refuses to return to center are also signals that your inner and outer tie rods should be checked and possibly replaced by a member of our service staff. Wheels out of alignment may be signs of bad inner or outer tie rods. As an outer tie rod fails, the toe changes direction and the steering begins to pull. Clicking or grinding noise under your front wheels are other signs of bad tie rods. If you experience any warning signs of a malfunctioning tie rod, give us a call or contact us online, and allow our service staff to determine if your steering system requires tie rod replacements.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
				<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Inner Tie Rod & Outer Tie Rod Replacement Services</h3>
				<p>Tires & Service
Regardless of the type of steering system in your vehicle, you use inner and outer tie rods. As an important part of your vehicle’s steering and suspension system, tie rods act as the link between your vehicle’s steering system and the steering arm, which is attached to the steering wheel. When you turn the steering wheel, the steering arm moves the front wheels through the steering system. The inner and outer tie rods connect to the steering arm in order to move the wheels of your vehicle. In the common rack-and-pinion steering system, the inner tie rods connect to the steering rack while the outer tie rods connect to the steering arms. The tie rods make steering and turning possible by moving your wheels in the desired direction. Without properly functioning tie rods, the steering mechanism would no longer operate as intended. Because inner and outer tie rods play such a significant role, replacing tie rods as necessary is important for overall vehicle maintenance.</p>
				<h3 class="text-blue">Why Should You Have Inner Tie Rod & Outer Tie Rod Replacement Services Performed?</h3>
				<p>Difficult, erratic, and unexpected steering are signs that your tie rods—inner, outer, or both—might need to be replaced. One indication that your tie rods may be loose is excessive and uneven tire wear. Vibrations and clunking noises emanating from the front of your vehicle are another sign. Steering that pulls or refuses to return to center are also signals that your inner and outer tie rods should be checked and possibly replaced by a member of our service staff. Wheels out of alignment may be signs of bad inner or outer tie rods. As an outer tie rod fails, the toe changes direction and the steering begins to pull. Clicking or grinding noise under your front wheels are other signs of bad tie rods. If you experience any warning signs of a malfunctioning tie rod, give us a call or contact us online, and allow our service staff to determine if your steering system requires tie rod replacements.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Tie Rod';
					var head_f = `Tie Rod`;
					var fre = `<h3 class="text-blue">Les bases derrière la biellette de direction intérieure et les services de remplacement de la biellette de direction extérieure</h3><p>Pneus et service Quel que soit le type de système de direction de votre véhicule, vous utilisez des biellettes de direction intérieure et extérieure. Composants essentiels du système de direction et de suspension de votre véhicule, les biellettes d’attelage servent de lien entre le système de direction de votre véhicule et le bras de direction, qui est fixé au volant. Lorsque vous tournez le volant, le bras de direction déplace les roues avant dans le système de direction. Les biellettes intérieure et extérieure se connectent au bras de direction afin de déplacer les roues de votre véhicule. Dans le système de direction à crémaillère commun, les biellettes intérieures se connectent à la crémaillère tandis que les biellettes extérieures se connectent aux bras de direction. Les biellettes rendent la direction et les virages possibles en déplaçant les roues dans la direction souhaitée. Si les biellettes ne fonctionnaient pas correctement, le mécanisme de direction ne fonctionnerait plus comme prévu. Étant donné que les biellettes intérieures et extérieures jouent un rôle si important, il est important de les remplacer, le cas échéant, pour l’entretien général du véhicule.</p><h3 class="text-blue">Pourquoi devriez-vous avoir des services de remplacement de biellette intérieure et de biellette extérieure réalisés?</h3><p>Une direction difficile, irrégulière et inattendue indique que vos biellettes de direction (intérieure, extérieure ou les deux) doivent éventuellement être remplacées. Une indication que vos biellettes est peut-être desserrée est une usure excessive et inégale des pneus. Les vibrations et les bruits de choc provenant de l'avant de votre véhicule sont un autre signe. Une direction qui tire ou refuse de revenir au centre indique également que vos biellettes intérieures et extérieures doivent être vérifiées et éventuellement remplacées par un membre de notre personnel de service. Des roues mal alignées peuvent être le signe d’une mauvaise biellette de direction interne ou externe. Lorsqu'un tirant extérieur tombe en panne, le pincement change de direction et la direction commence à tirer. Les bruits de cliquetis ou de grincement sous les roues avant sont d’autres signes de mauvaises biellettes. Si vous rencontrez des signes avant-coureurs d'un tirant défectueux, appelez-nous ou contactez-nous en ligne pour permettre à notre personnel de service en charge de déterminer si votre système de direction nécessite un remplacement du tirant.<br><br><span class="text-danger">Approx. Time: 60 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>

<?php
}
 else if ($_GET['pg'] == 'Shocks-Replacement') {
?>
						<h3 class="text-blue">The Basics Behind Shocks Replacement Services</h3>
				<p>Shock absorbers are components in your vehicle’s suspension system that help your tires remain in contact with the surface of the road. They dampen the impact of road force and absorb the rebound of springs and other suspension components. Front and rear shocks are designed to adjust to driving conditions, like bumps, potholes, and sudden maneuvers. They also reduce bounce rate, sway, and brake dive or acceleration squat. Modern day shocks are velocity-sensitive, which means that the faster the springs and other suspension components are moving, the more resistance provided by the shocks. Hydraulic shocks convert kinetic energy from the springs into thermal energy that the hydraulic fluid inside each shock absorbs and dissipates. When the suspension system bounces, hydraulic fluid is forced through holes inside the piston. This slows the compression of the piston, thereby slowing down spring and suspension movement. While hydraulic and gas shocks are the most common types of shocks used on vehicles today, some vehicles also use electronic and air shocks.</p>
				<h3 class="text-blue">Why Should You Have Shocks Replacement Services Performed?</h3>
				<p>Replacing shocks can maximize the performance of your entire suspension system. The components in your suspension system interact and depend on each other. Shock absorbers and brakes work together to help your vehicle stop as soon as possible upon engaging the brake pedal. Worn shocks mean your vehicle is less likely to stop exactly when and where you want. In fact, bad shocks can increase your stopping distance by up to 10 feet. Worn shock absorbers will cause your vehicle to dive when braking. With a set of bad shocks, you may experience problems like bounce, body roll, sway, and other unexpected movements in your suspension system. Healthy shocks improve braking and handling, making your vehicle easier to control. Replacing front and rear shocks as necessary will help promote a safe road for everyone.<br><br><span class="text-danger">Approx. Time: 120 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
				<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Shocks Replacement Services</h3>
				<p>Shock absorbers are components in your vehicle’s suspension system that help your tires remain in contact with the surface of the road. They dampen the impact of road force and absorb the rebound of springs and other suspension components. Front and rear shocks are designed to adjust to driving conditions, like bumps, potholes, and sudden maneuvers. They also reduce bounce rate, sway, and brake dive or acceleration squat. Modern day shocks are velocity-sensitive, which means that the faster the springs and other suspension components are moving, the more resistance provided by the shocks. Hydraulic shocks convert kinetic energy from the springs into thermal energy that the hydraulic fluid inside each shock absorbs and dissipates. When the suspension system bounces, hydraulic fluid is forced through holes inside the piston. This slows the compression of the piston, thereby slowing down spring and suspension movement. While hydraulic and gas shocks are the most common types of shocks used on vehicles today, some vehicles also use electronic and air shocks.</p>
				<h3 class="text-blue">Why Should You Have Shocks Replacement Services Performed?</h3>
				<p>Replacing shocks can maximize the performance of your entire suspension system. The components in your suspension system interact and depend on each other. Shock absorbers and brakes work together to help your vehicle stop as soon as possible upon engaging the brake pedal. Worn shocks mean your vehicle is less likely to stop exactly when and where you want. In fact, bad shocks can increase your stopping distance by up to 10 feet. Worn shock absorbers will cause your vehicle to dive when braking. With a set of bad shocks, you may experience problems like bounce, body roll, sway, and other unexpected movements in your suspension system. Healthy shocks improve braking and handling, making your vehicle easier to control. Replacing front and rear shocks as necessary will help promote a safe road for everyone.<br><br><span class="text-danger">Approx. Time: 120 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Shocks-Replacement';
					var head_f = `Chocs-Remplacement`;
					var fre = `<h3 class="text-blue">L'essentiel des services de remplacement des chocs</h3><p>Les amortisseurs sont des composants du système de suspension de votre véhicule qui permettent à vos pneus de rester en contact avec la surface de la route. Ils amortissent l'impact de la force de la route et absorbent le rebond des ressorts et des autres composants de la suspension. Les amortisseurs avant et arrière sont conçus pour s'adapter aux conditions de conduite, telles que bosses, nids de poule et manœuvres soudaines. Ils réduisent également le taux de rebond, le balancement et le piqué des freins ou l'accélération. Les chocs modernes sont sensibles à la vitesse, ce qui signifie que plus les ressorts et les autres composants de la suspension bougent rapidement, plus les chocs apportent de la résistance. Les chocs hydrauliques convertissent l'énergie cinétique des ressorts en énergie thermique que le fluide hydraulique à l'intérieur de chaque choc absorbe et dissipe. Lorsque le système de suspension rebondit, le fluide hydraulique est forcé à travers les trous à l'intérieur du piston. Cela ralentit la compression du piston, ralentissant ainsi le mouvement du ressort et de la suspension. Alors que les chocs hydrauliques et à gaz sont les types de chocs les plus couramment utilisés sur les véhicules actuels, certains véhicules utilisent également des chocs électroniques et pneumatiques.</p><h3 class="text-blue">Pourquoi devriez-vous faire exécuter des services de remplacement des chocs?</h3><p>Le remplacement des amortisseurs peut optimiser les performances de l’ensemble du système de suspension. Les composants de votre système de suspension interagissent et dépendent les uns des autres. Les amortisseurs et les freins travaillent ensemble pour aider votre véhicule à s'arrêter dès que possible lorsque vous appuyez sur la pédale de frein. Les chocs usés signifient que votre véhicule est moins susceptible de s’arrêter exactement où et quand vous le souhaitez. En fait, les chocs violents peuvent augmenter votre distance d’arrêt de 10 pieds. Des amortisseurs usés feront plonger votre véhicule lors du freinage. Avec une série de chocs violents, vous risquez de rencontrer des problèmes de rebond, de roulis, d’oscillation et d’autres mouvements inattendus dans votre système de suspension. Des chocs sains améliorent le freinage et la maniabilité, facilitant ainsi le contrôle de votre véhicule. Le remplacement des amortisseurs avant et arrière si nécessaire contribuera à promouvoir une route sûre pour tous.<br><br><span class="text-danger">Approx. Time: 120 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>

<?php
}
 else if ($_GET['pg'] == 'Struts-Replacement') {
?>
						<h3 class="text-blue">The Basics Behind Struts Replacement Services</h3>
				<p>While the function of shocks and struts is very similar, the biggest difference is in how they mount to your vehicle. Shocks function in addition to other suspension components, while struts are designed as a pivot point for the steering mechanism. Struts behave as a dampening device that absorbs excessive bounce. The strut assembly combines coil springs, spring seats, strut bearings, and shock absorbers into one working unit. The steering arm or steering knuckle is also included in some strut designs. Struts use a piston to absorb high lateral loads. The spring seat and strut bearing allow the shock to pivot with the front wheels and the steering mechanism. Struts and accompanying suspension components help push tires back into place when one leaves the road. Overall, struts work in conjunction with the rest of the suspension system to help stabilize the vehicle while maintaining a comfortable and safe ride.</p>
				<h3 class="text-blue">Why Should You Have Struts Replacement Services Performed?</h3>
				<p>Worn struts increase braking distance and increase body roll, sway, and bounce rate. The bounce test, wherein you bounce on each corner of your vehicle a few times, is a good way to determine whether or not you need to schedule a strut replacement. If your vehicle bounces and settles, your struts are operating as they should. If your vehicle continues to bounce, you should seek to replace the struts on your suspension system as soon as possible. Other signs that your struts need to be replaced include excessive brake dive, acceleration squat, body roll or sway, and unusual tire wear patterns. Unusual noise from struts may also indicate that the spring seat or strut bearing requires a replacement. If you experience any of the above signs of worn struts, contact us immediately. Having your struts replaced will improve braking, handling, and the overall controllability of your vehicle.<br><br><span class="text-danger">Approx. Time: 120 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
				<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Struts Replacement Services</h3>
				<p>While the function of shocks and struts is very similar, the biggest difference is in how they mount to your vehicle. Shocks function in addition to other suspension components, while struts are designed as a pivot point for the steering mechanism. Struts behave as a dampening device that absorbs excessive bounce. The strut assembly combines coil springs, spring seats, strut bearings, and shock absorbers into one working unit. The steering arm or steering knuckle is also included in some strut designs. Struts use a piston to absorb high lateral loads. The spring seat and strut bearing allow the shock to pivot with the front wheels and the steering mechanism. Struts and accompanying suspension components help push tires back into place when one leaves the road. Overall, struts work in conjunction with the rest of the suspension system to help stabilize the vehicle while maintaining a comfortable and safe ride.</p>
				<h3 class="text-blue">Why Should You Have Struts Replacement Services Performed?</h3>
				<p>Worn struts increase braking distance and increase body roll, sway, and bounce rate. The bounce test, wherein you bounce on each corner of your vehicle a few times, is a good way to determine whether or not you need to schedule a strut replacement. If your vehicle bounces and settles, your struts are operating as they should. If your vehicle continues to bounce, you should seek to replace the struts on your suspension system as soon as possible. Other signs that your struts need to be replaced include excessive brake dive, acceleration squat, body roll or sway, and unusual tire wear patterns. Unusual noise from struts may also indicate that the spring seat or strut bearing requires a replacement. If you experience any of the above signs of worn struts, contact us immediately. Having your struts replaced will improve braking, handling, and the overall controllability of your vehicle.<br><br><span class="text-danger">Approx. Time: 120 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Struts-Replacement';
					var head_f = `Remplacement de jambes de force`;
					var fre = `<h3 class="text-blue">Les bases derrière les services de remplacement de Struts</h3><p>Bien que la fonction des amortisseurs et des jambes de suspension soit très similaire, la plus grande différence réside dans la manière dont ils sont montés sur votre véhicule. Les amortisseurs fonctionnent en plus des autres composants de la suspension, tandis que les jambes de force sont conçues comme un pivot pour le mécanisme de direction. Les jambes de force se comportent comme un dispositif amortisseur qui absorbe les rebonds excessifs. L'assemblage de jambe de force combine des ressorts hélicoïdaux, des sièges de ressort, des paliers de jambe de force et des amortisseurs en une seule unité de travail. Le bras de direction ou la fusée de direction est également inclus dans certaines conceptions de jambe de force. Les jambes de force utilisent un piston pour absorber les fortes charges latérales. Le siège à ressort et le palier de jambe de suspension permettent à l'amortisseur de pivoter avec les roues avant et le mécanisme de direction. Les jambes de force et les composants de suspension qui l'accompagnent aident à remettre les pneus en place lorsque l'on quitte la route. Globalement, les jambes de force fonctionnent conjointement avec le reste du système de suspension pour aider à stabiliser le véhicule tout en maintenant une conduite confortable et sûre.</p><h3 class="text-blue">Pourquoi devriez-vous faire exécuter des services de remplacement de Struts?</h3><p>Les jambes de force usées augmentent la distance de freinage et augmentent le roulis, le balancement et le taux de rebond. Le test de rebond, dans lequel vous rebondissez plusieurs fois à chaque coin de votre véhicule, est un bon moyen de déterminer si vous devez ou non planifier un remplacement de jambe de suspension. Si votre véhicule rebondit et se stabilise, vos jambes de force fonctionnent comme elles le devraient. Si votre véhicule continue de rebondir, vous devez essayer de remplacer les jambes de force de votre système de suspension dès que possible. Les autres signes indiquant que vos jambes de force doivent être remplacées incluent une chute excessive des freins, un squat d'accélération, un roulis ou un balancement, et une usure inhabituelle des pneus. Un bruit inhabituel provenant des jambes de force peut également indiquer que le siège à ressort ou le palier de jambe de force nécessite un remplacement. Si vous ressentez l’un des signes susmentionnés de jambes de force usées, contactez-nous immédiatement. Le remplacement de vos jambes améliorera le freinage, la maniabilité et la contrôlabilité globale de votre véhicule.<br><br><span class="text-danger">Approx. Time: 120 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>

<?php
}
 else if ($_GET['pg'] == 'Suspension-Inspection') {
?>
						<h3 class="text-blue">The Basics Behind Suspension Inspection Services</h3>
				<p>The primary function of your vehicle’s suspension system is to provide structural support while maintaining comfortable riding conditions. The suspension system helps your vehicle’s tires maintain firm contact on the road at all times by compensating for bumps, potholes, and sudden undulations. Suspension system components like coil springs, leaf springs, torsion bars, shocks, and struts all help to absorb bounce, shock, and unexpected motion from the surface of the road. Without a fully functioning suspension system, your vehicle will be harder to control. Because regular wear and tear takes its toll on your suspension system, the scheduling of routine repairs and an understanding of the signs of an impending service are an important part of suspension system maintenance. For example, experiencing unusual movements over bumps or through turns are signs that your suspension system should be inspected by a staff of professionals. When you suspect suspension system problems, please give us a call or contact us.</p>
				<h3 class="text-blue">Why Should You Have Suspension Inspection Services Performed?</h3>
				<p>Knowing how to identify steering and suspension issues will help you determine when to schedule an inspection. Over time, the components of your suspension system, like coil springs, shock absorbers, struts, shocks, tie rods, ball joints, and sway bar links, can weaken and malfunction, thereby decreasing your ability to maintain control of your vehicle. Signs of an impending suspension inspection include leaking shocks or struts. Nose-dives when braking and bottoming out during bumps are also signs of a problem with your vehicle’s suspension system. If you begin to experience driving irregularities like bouncing, swaying, or unusual stiffness, contact us today for an inspection of your steering and suspension system. Besides being aware of the signs and symptoms of a worn suspension system, be sure to consult your owner’s manual when determining maintenance schedules and intervals for inspections of your vehicle’s suspension system.<br><br><span class="text-danger">Approx. Time: 30 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
				<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Suspension Inspection Services</h3>
				<p>The primary function of your vehicle’s suspension system is to provide structural support while maintaining comfortable riding conditions. The suspension system helps your vehicle’s tires maintain firm contact on the road at all times by compensating for bumps, potholes, and sudden undulations. Suspension system components like coil springs, leaf springs, torsion bars, shocks, and struts all help to absorb bounce, shock, and unexpected motion from the surface of the road. Without a fully functioning suspension system, your vehicle will be harder to control. Because regular wear and tear takes its toll on your suspension system, the scheduling of routine repairs and an understanding of the signs of an impending service are an important part of suspension system maintenance. For example, experiencing unusual movements over bumps or through turns are signs that your suspension system should be inspected by a staff of professionals. When you suspect suspension system problems, please give us a call or contact us.</p>
				<h3 class="text-blue">Why Should You Have Suspension Inspection Services Performed?</h3>
				<p>Knowing how to identify steering and suspension issues will help you determine when to schedule an inspection. Over time, the components of your suspension system, like coil springs, shock absorbers, struts, shocks, tie rods, ball joints, and sway bar links, can weaken and malfunction, thereby decreasing your ability to maintain control of your vehicle. Signs of an impending suspension inspection include leaking shocks or struts. Nose-dives when braking and bottoming out during bumps are also signs of a problem with your vehicle’s suspension system. If you begin to experience driving irregularities like bouncing, swaying, or unusual stiffness, contact us today for an inspection of your steering and suspension system. Besides being aware of the signs and symptoms of a worn suspension system, be sure to consult your owner’s manual when determining maintenance schedules and intervals for inspections of your vehicle’s suspension system.<br><br><span class="text-danger">Approx. Time: 30 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Suspension-Inspection';
					var head_f = `Inspection de suspension`;
					var fre = `<h3 class="text-blue">L'essentiel des services d'inspection des suspensions</h3><p>La fonction principale du système de suspension de votre véhicule est de fournir un soutien structurel tout en maintenant des conditions de conduite confortables. Le système de suspension aide les pneus de votre véhicule à maintenir un contact ferme sur la route en tout temps en compensant les bosses, les nids-de-poule et les ondulations soudaines. Les composants du système de suspension tels que les ressorts hélicoïdaux, les ressorts à lames, les barres de torsion, les amortisseurs et les jambes de force aident tous à absorber les rebonds, les chocs et les mouvements inattendus de la surface de la route. Sans système de suspension entièrement fonctionnel, votre véhicule sera plus difficile à contrôler. Étant donné que l'usure régulière affecte votre système de suspension, la planification des réparations de routine et la compréhension des signes d'un service imminent constituent un élément important de la maintenance du système de suspension. Par exemple, des mouvements inhabituels sur des bosses ou dans les virages indiquent que votre système de suspension doit être inspecté par une équipe de professionnels. Si vous suspectez un problème de système de suspension, appelez-nous ou contactez-nous.</p><h3 class="text-blue">Pourquoi devriez-vous faire effectuer des services d'inspection de suspension?</h3><p>Knowing how to identify steering and suspension issues will help you determine when to schedule an inspection. Over time, the components of your suspension system, like coil springs, shock absorbers, struts, shocks, tie rods, ball joints, and sway bar links, can weaken and malfunction, thereby decreasing your ability to maintain control of your vehicle. Signs of an impending suspension inspection include leaking shocks or struts. Nose-dives when braking and bottoming out during bumps are also signs of a problem with your vehicle’s suspension system. If you begin to experience driving irregularities like bouncing, swaying, or unusual stiffness, contact us today for an inspection of your steering and suspension system. Besides being aware of the signs and symptoms of a worn suspension system, be sure to consult your owner’s manual when determining maintenance schedules and intervals for inspections of your vehicle’s suspension system.<br><br><span class="text-danger">Approx. Time: 30 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>

<?php
}
 else if ($_GET['pg'] == 'Sway-Bar-Link') {
?>
						<h3 class="text-blue">The Basics Behind Sway Bar Link Replacement Services</h3>
				<p>Connecting the wheels on opposite sides of the vehicle is a stabilizer bar called the sway bar. The sway bar is charged with controlling “body roll” by distributing the weight of your vehicle to both sides of the suspension. When your vehicle moves through a turn, the sway bar keeps the vehicle level by minimizing body roll through the transfer of vehicle weight to the outside wheels. It also maintains solid contact with the surface of the road through the compression of the suspension components on the inside wheels. Sway bar links are a crucial component in your vehicle’s suspension system. The sway bar links are what connect the suspension to the sway bar and transfer the force of motion from the wheels to the axles. When the vehicle turns or corners, the sway bar end links pull on the bar to resist body roll while stabilizing the force of motion and the weight of the vehicle.</p>
				<h3 class="text-blue">Why Should You Have Sway Bar Link Replacement Services Performed?</h3>
				<p>Because sway bar links are responsible for transferring the force of motion from the wheels to the sway bar and to the rest of the suspension system, if a sway bar end link is damaged, the controllability of your vehicle and the safety of your passengers are at risk. While some sway bar links have bushing that can be replaced, other sway bar links require replacements upon wearing out. Warning signs of a broken or bad sway bar link include clunks and squeaks. Over-steering or excessive lean through turns are also symptoms of worn sway bar links, but they can also be signs of larger problems with your vehicle’s suspension system. Do not let symptoms of bad sway bar links or other suspension components go untreated. Little problems with suspension systems have the tendency to turn into larger problems and more expensive repairs if not repaired or replaced. If you experience any of the above symptoms, allow our service staff to determine if a sway bar link replacement is right for you.<br><br><span class="text-danger">Approx. Time: 30 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>
				<script type="text/javascript">
					var eng = `<h3 class="text-blue">The Basics Behind Sway Bar Link Replacement Services</h3>
				<p>Connecting the wheels on opposite sides of the vehicle is a stabilizer bar called the sway bar. The sway bar is charged with controlling “body roll” by distributing the weight of your vehicle to both sides of the suspension. When your vehicle moves through a turn, the sway bar keeps the vehicle level by minimizing body roll through the transfer of vehicle weight to the outside wheels. It also maintains solid contact with the surface of the road through the compression of the suspension components on the inside wheels. Sway bar links are a crucial component in your vehicle’s suspension system. The sway bar links are what connect the suspension to the sway bar and transfer the force of motion from the wheels to the axles. When the vehicle turns or corners, the sway bar end links pull on the bar to resist body roll while stabilizing the force of motion and the weight of the vehicle.</p>
				<h3 class="text-blue">Why Should You Have Sway Bar Link Replacement Services Performed?</h3>
				<p>Because sway bar links are responsible for transferring the force of motion from the wheels to the sway bar and to the rest of the suspension system, if a sway bar end link is damaged, the controllability of your vehicle and the safety of your passengers are at risk. While some sway bar links have bushing that can be replaced, other sway bar links require replacements upon wearing out. Warning signs of a broken or bad sway bar link include clunks and squeaks. Over-steering or excessive lean through turns are also symptoms of worn sway bar links, but they can also be signs of larger problems with your vehicle’s suspension system. Do not let symptoms of bad sway bar links or other suspension components go untreated. Little problems with suspension systems have the tendency to turn into larger problems and more expensive repairs if not repaired or replaced. If you experience any of the above symptoms, allow our service staff to determine if a sway bar link replacement is right for you.<br><br><span class="text-danger">Approx. Time: 30 Minutes</span></p>
				<a href="appoinment.php" class="btn-blue btn">Appoinment</a>`;
					var head_e = 'Sway-Bar-Link';
					var head_f = `Barre stabilisatrice lien`;
					var fre = `<h3 class="text-blue">L'essentiel des services de remplacement de liaison de barre stabilisatrice</h3><p>Une barre stabilisatrice appelée barre stabilisatrice relie les roues sur les côtés opposés du véhicule. La barre stabilisatrice est chargée de contrôler le roulis en répartissant le poids de votre véhicule sur les deux côtés de la suspension. Lorsque votre véhicule effectue un virage, la barre stabilisatrice maintient le niveau du véhicule en minimisant le roulis lors du transfert du poids du véhicule sur les roues extérieures. Il maintient également un contact solide avec la surface de la route grâce à la compression des composants de la suspension sur les roues intérieures. Les barres de stabilisation sont un élément essentiel du système de suspension de votre véhicule. Les liens de barre stabilisatrice sont ce qui relie la suspension à la barre stabilisatrice et transfère la force de mouvement des roues aux essieux. Lorsque le véhicule tourne ou tourne dans les coins, les bras d’extrémité de la barre stabilisatrice tirent sur la barre pour résister au roulis tout en stabilisant la force de déplacement et le poids du véhicule.</p><h3 class="text-blue">Pourquoi devriez-vous faire exécuter les services de remplacement de la barre stabilisatrice?</h3><p>Parce que les barres stabilisatrices sont responsables du transfert de la force de mouvement des roues vers la barre stabilisatrice et le reste du système de suspension, si une biellette d'extrémité de barre stabilisatrice est endommagée, la maniabilité de votre véhicule et la sécurité de vos passagers risque. Certaines bagues de barre stabilisatrice ont des bagues qui peuvent être remplacées, d'autres doivent être remplacées lors de l'usure. Les signes avant-coureurs d’un lien de barre d’antenne cassé ou mauvais incluent des grincements et des grincements. Un excès de braquage ou une inclinaison excessive dans les virages sont également des symptômes de maillons de barre stabilisatrice usés, mais ils peuvent également indiquer des problèmes plus importants liés au système de suspension de votre véhicule. Ne laissez pas les symptômes de mauvaises barres stabilisatrices ou d’autres composants de la suspension non traités. Peu de problèmes avec les systèmes de suspension ont tendance à se transformer en problèmes plus importants et en réparations plus coûteuses s’ils ne sont pas réparés ou remplacés. Si vous présentez l'un des symptômes ci-dessus, laissez notre personnel de maintenance déterminer si le remplacement de la barre stabilisatrice vous convient.<br><br><span class="text-danger">Approx. Time: 30 Minutes</span></p><a href="appoinment.php" class="btn-blue btn">RENDEZ-VOUS</a>`;

				</script>

<?php
}
?>
</div>
</div>
</div>
<script type="text/javascript">
	var head = document.getElementById('head');
	var elem = document.getElementById('trans');
function lang_trans() {
		var lng = document.getElementById('lang').value;
		if (lng == 'fre') {
		head.innerHTML = head_f;
		trans.innerHTML = fre;
		}
		else if (lng = 'eng'){
		head.innerHTML = head_e;
		trans.innerHTML = eng;
		}

	}
</script>
<?php
}
require 'footer.php';
?>